changelog:
  categories:
    - title: 🏕 Features
      labels:
        - feature
        - enhancement
        - feat
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
        - bugfix
        - fixes
