---
exclude: docs|node_modules|migrations|.git|.tox|chart
default_stages: [commit]
fail_fast: true

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.1.3
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix, --ignore=E501]

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.32.0
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
