# Generated by Django 4.2.7 on 2023-11-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuni_italiani', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comune',
            name='auto_code',
        ),
        migrations.AddField(
            model_name='provincia',
            name='auto_code',
            field=models.CharField(blank=True, help_text='Sigla automobilistica', max_length=2, null=True, verbose_name='Sigla automobilistica'),
        ),
    ]
