# Generated by Django 4.2.7 on 2023-11-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuni_italiani', '0003_alter_comune_options_alter_provincia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comune',
            name='geographic_partition',
            field=models.CharField(help_text='Ripartizione geografica', max_length=255, null=True, verbose_name='Ripartizione geografica'),
        ),
    ]
